services:
  home_inventory:
    build: .
    container_name: home_inventory_container
    restart: always
    command: [ "sh", "-c", "npm install && npm start" ]
    environment:
      - PORT=${PORT}
      - MONGO_URL=mongodb://home_inventory_mongo:27017/${DB_NAME}
      - DEFAULT_APP_USER=${DEFAULT_APP_USER}
      - DEFAULT_ADD_EMAIL=${DEFAULT_ADD_EMAIL}
      - DEFAULT_APP_PASSWORD=${DEFAULT_APP_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET}
    networks:
      - HomeInventory-net

  home_inventory_mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - home_inventory_mongo_data:/data/inventory_db
    expose:
      - "27017"
    networks: [ HomeInventory-net ]

volumes:
  home_inventory_mongo_data: {}

networks:
  HomeInventory-net:
    external: true