name: Deploy Home Inventory

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Update Code and Redeploy
        #execute all commands from project's directory
        working-directory: /home/homeadmin/subApps/HomeInventory
        run: |
          # Pull the latest code from the main branch
          git fetch origin
          git reset --hard origin/prod

          # destroy the current version of the website without wiping the DB
          docker compose down

          # re-compose the website
          docker compose up -d --build